#!/bin/bash

function usage() {
	cat <<-EOF
	USAGE: ${0} [OPTIONS]

	DESCRIPTION:

    This script kicks off all the integration tests. It can be run against local or remote
    services. By default, it will run against local services.

	OPTIONS:

        -h:   Display this documentation

        -e:   Takes an environement argument to specify which endpoints
              to hit.

        -t:   Sets whether a tunnel to the staging identity service is
              needed.

	ENVIRONMENTS:

        stage | staging

	EXAMPLES:

        # Run against local services by default
        ${0}

        # Run against staging environment
        ${0} -e staging

	EOF
}

function main() {
    # source test helpers
    . ysh/helpers.sh

    # Run tests starting with test_
    RunTests 
}

SHUNIT_TEST_PREFIX="[TEST] "

while getopts ":thve:" opt; do
  case $opt in
    e)
        case ${OPTARG} in
            "staging"|"stage")
                TUNNEL_REQUIRED=true
                LOCAL_RUN=false
                REST_API=${S_REST_API}
                RPC_API=${S_RPC_API}
                METRICS_API=${S_METRICS_API}
		AUTHSERVICE=${S_AUTHSERVICE}
                ;;
            *)
                usage
                ;;
        esac
        ;;
    h)
        usage
        exit 0
        ;;
    t)
	    TUNNEL_REQUIRED=true
        ;;
    v)
        VERBOSE=true
        ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done


###
# Main
###

main "${@}"
